// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201111212515_DbCreation01")]
    partial class DbCreation01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("DAL.DbGameData", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivePlayerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AllowedPlacementType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InactivePlayerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipSizesDbFriendly")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WinningPlayer")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ActivePlayerID");

                    b.HasIndex("InactivePlayerID");

                    b.ToTable("StateSave");
                });

            modelBuilder.Entity("DAL.DbPlayerDTO", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardDbFriendly")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHorizontalPlacement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsViewingOwnBoard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PPlayerDbFriendly")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipBeingPlacedIdx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipsDbFriendly")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShootingHistoryDbFriendly")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("fOffsetX")
                        .HasColumnType("REAL");

                    b.Property<float>("fOffsetY")
                        .HasColumnType("REAL");

                    b.Property<float>("fScaleX")
                        .HasColumnType("REAL");

                    b.Property<float>("fScaleY")
                        .HasColumnType("REAL");

                    b.Property<float>("fSelectedTileX")
                        .HasColumnType("REAL");

                    b.Property<float>("fSelectedTileY")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("DAL.DbGameData", b =>
                {
                    b.HasOne("DAL.DbPlayerDTO", "ActivePlayer")
                        .WithMany()
                        .HasForeignKey("ActivePlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.DbPlayerDTO", "InactivePlayer")
                        .WithMany()
                        .HasForeignKey("InactivePlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
